version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: parkshare_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vasanth@123
      POSTGRES_DB: parkshare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: parkshare_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:Vasanth%40123@postgres:5432/parkshare
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ENVIRONMENT=production
      - DEBUG=False
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: parkshare_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
